name: example
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  build_runner: ">=1.10.0 <2.0.0"
  assets_gen:
    path: ../

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets2/
    - assets/2x/
    - assets/3.0x/
    - assets/1.txt
    - assets/sub/
    - assets/exclude/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

assets_gen:
  output: assets.g.dart
  class_name: Assets
  gen_package_path: true
  ignore_resolution: true
  omit_path_levels: 0
  exclude:
    - assets/exclude/*