name: example
description: assets_gen examble project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sub1:
    path: sub1/

dev_dependencies:
  build_runner: ">=1.10.0 <2.0.0"
  assets_gen:
    path: ../

flutter:
  assets:
    - assets/
    - assets/2x/
    - assets/3.0x/
    - assets/exclude/
    - assets/images/
    - assets/vip/
    - assets/1.txt
    - assets2/

assets_gen:
  output: assets.dart
  class_name: Assets
  gen_package_path: true
  ignore_resolution: true
  omit_path_levels: 0
  exclude:
    - assets/exclude/*
  plurals:
    - assets/vip/*.svg