# https://github.com/dart-lang/build/blob/master/build_config/README.md
# https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md
# https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/options.dart
# https://github.com/dart-lang/glob

targets:
  $default:
    builders:
      assets_gen|assets_builder:
        enabled: true

builders:
  assets_builder:
    import: "package:assets_gen/assets_gen.dart"
    builder_factories: ["assetsBuilder"]
    build_extensions: {"$lib$": ["assets.g.dart"]}
    build_to: source
    auto_apply: dependents