// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'example';

  static const String assets_1_txt = 'assets/1.txt';
  static const String example$assets_1_txt = 'packages/example/assets/1.txt';

  static const String assets_images_flutter_png = 'assets/images/flutter.png';
  static const String example$assets_images_flutter_png = 'packages/example/assets/images/flutter.png';

  static String assets_vip_x_svg(Object p0) => 'assets/vip/${p0.toString()}.svg';
  static String example$assets_vip_x_svg(Object p0) => 'packages/example/assets/vip/${p0.toString()}.svg';

  static const String assets2_2_txt = 'assets2/2.txt';
  static const String example$assets2_2_txt = 'packages/example/assets2/2.txt';
}
