// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'example';

  static const String assets_1_txt = 'assets/1.txt';
  static const String example$assets_1_txt = 'packages/example/assets/1.txt';

  static const String assets_flutter_png = 'assets/flutter.png';
  static const String example$assets_flutter_png = 'packages/example/assets/flutter.png';

  static const String assets_sub_sub1_txt = 'assets/sub/sub1.txt';
  static const String example$assets_sub_sub1_txt = 'packages/example/assets/sub/sub1.txt';

  static const String assets2_2_txt = 'assets2/2.txt';
  static const String example$assets2_2_txt = 'packages/example/assets2/2.txt';
}
