// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 6.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'example';

  static const String assets_1_txt = 'assets/1.txt';
  static const String example$assets_1_txt = 'packages/example/assets/1.txt';

  static const String assets_A_teST_fiLE___Light_json_json = 'assets/A_teST_fiLE_-_Light.json.json';
  static const String example$assets_A_teST_fiLE___Light_json_json = 'packages/example/assets/A_teST_fiLE_-_Light.json.json';

  static const String assets_File_contains_blank_txt = 'assets/File contains blank.txt';
  static const String example$assets_File_contains_blank_txt = 'packages/example/assets/File contains blank.txt';

  static const String assets_images_flutter_png = 'assets/images/flutter.png';
  static const String example$assets_images_flutter_png = 'packages/example/assets/images/flutter.png';

  static String assets_vip_x_svg(Object p0) => 'assets/vip/${p0.toString()}.svg';

  static String example$assets_vip_x_svg(Object p0) => 'packages/example/assets/vip/${p0.toString()}.svg';

  static const String assets2_2_txt = 'assets2/2.txt';
  static const String example$assets2_2_txt = 'packages/example/assets2/2.txt';
}
