// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'sub1';

  static const String assets_1_txt = 'assets/1.txt';
  static const String sub1$assets_1_txt = 'packages/sub1/assets/1.txt';
}
